PRA-26 Сверстать страницу лидерборда
Kirill2511/client-server-template-with-vite pull request #11
Opened 2022-10-07 11:16 UTC by zayarnaya

### Сверстать страницу лидерборда

![LB_screen](https://user-images.githubusercontent.com/12728467/194540684-216798f2-39d5-4a64-b7e7-781b4b70b68a.png)

**Компоненты**:
- StaticLayout: обертка для моих широких страниц. Берет в качестве аргумента content ReactNode с собственно содержимым. Живет в "/src/components/StaticLayout/" 
В ней есть два компонента:
-- LeftPanel: левая панелька с кнопкой возврата к игре. Пока не работает за отсутствием общего роутера. Живет в "/src/components/StaticLayout/LeftPanel/";
-- UpperMenu: Живет в "/src/components/UpperMenu/", верхнее меню, в которое включено собственно меню с NavLinks (жирненькие, пока не работают, у себя проверяла на прописанных роутах), переключалка Ночная-Дневная тема (пока не работает, только саму надпись меняет), выход (теоретически работает, просто посылает запрос по logout, больше ничего не делает); делаются через компонент UpperMenuItem (живет в "/src/components/UpperMenu/UpperMenuItem/", в зависимости от аргумента рендерит navlink либо текст с onClick). В меню слева располагается компонент 
--- UserInfo: Живет в "/src/components/UpperMenu/UpperMenuUserInfo/", берет аргументом выдачу API по запросу Get User (пока заполняется из dummy-константы). В нем использован компонент 
----UserAvatar: Живет в "/src/components/UserAvatar/", представляет собой немного переработанный Avatar (добавлена установка своего класса, условный рендер текста в зависимости от наличия оного).

- LeaderBoard: передается в StaticLayout, живет в "/src/components/Leaderboard/Leaderboard/", использует компонент
-- LeaderBoardItem: элемент списка лидеров, аргументами берет url аватарки, имя пользователя и кол-во очков (пока заполняется из dummy-константы). Аватар делается через UserAvatar.

**Стили**
Заложена темная тема. Имена классов заданы как попало, я старалась придерживаться БЭМ, но не везде получилось (предложения по переименованию принимаются с благодарностью).
Часть стилей вынесена отдельно и вообще не в идеологии ("/src/styles/style.scss"), клятвенно обещаю с ними разобраться к сдаче следующего таска.

**Проблемы**
Не понимаю, почему у меня задваивается рендер.

2022-10-07 11:21 UTC, Kirill2511 commented on packages/client/src/components/Leaderboard/LeaderItem/LeaderItem.tsx
> +  onClick = () => console.log('ТУТ БУДЕТ ССЫЛКА НА ПРОФИЛЬ'),
Тут ведь пропс, зачем консоль лог?)

2022-10-07 11:25 UTC, Kirill2511 commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.scss
> +.leaderboard-top-list {
аналогично как выше, leaderboard_top-list (если это модификатор)

2022-10-07 11:26 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/LeaderItem/LeaderItem.tsx
> +  onClick = () => console.log('ТУТ БУДЕТ ССЫЛКА НА ПРОФИЛЬ'),
Заглушка пока ) Чтобы не забыть, где правильные ссылки/функции расставить. У меня на всех или почти на всех элементах с действиями такие заглушки стоят

2022-10-07 11:28 UTC, Kirill2511 commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.tsx
> +  const title = props.title ? props.title : 'Доска почета';
Можно проще, вместо (props) -- title = Доска почета, т.е. если не задан title то он будет аналогично коду ниже работать.

2022-10-07 11:30 UTC, Kirill2511 commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +  const { content } = props;
export const StaticLayout: React.FC<StaticLayoutProps> = ({ content }) => {
лишняя строчка)

2022-10-07 11:31 UTC, Kirill2511 commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +      {content}
тут лучше будет children, он как раз для этого и существует.

2022-10-07 12:33 UTC, zayarnaya commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +  const { content } = props;
Done

2022-10-07 12:33 UTC, zayarnaya commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +      {content}
Done

2022-10-07 12:36 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.scss
> +.leaderboard-wrapper {
Ага ))

2022-10-07 12:36 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.scss
> +.leaderboard-top-list {
Элемент, если я правильно понимаю

2022-10-09 17:44 UTC, deadem requested changes
Кажется тут путаница в файлах, компонентах и блоках произошла. Что от чего зависит и что куда писать.
Предлагаю небольшой мастер-класс провести на тему с какой стороны к этому всему подходить, и как справляться с зависимостями. Если интересно, предлагаю в чатике договориться по времени - может быть кому-то ещё будет полезно.

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/Leaderboard/LeaderItem/LeaderItem.tsx
> +      <div className="score_theme_light">{score}</div>
В общем, тут везде БЭМ сломан

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.scss
> +.leaderboard__wrapper {
Про это говорили в чатике. Что телега впереди лошади получилась ;)

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.tsx
> +    <div className="leaderboard__wrapper_theme_light">
Тут те же проблемы с разбиением на Блоки, что и в предыдущем файле.

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/StaticLayout/LeftPanel/LeftPanel.scss
> +.link-to-game {
Блок и имя файла разбежались. Называется файл - панель, а внутри ссылка на игру...

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/StaticLayout/LeftPanel/LeftPanel.scss
> +  height: 28px !important;
Понадобился important - значит есть косяк с описанием стилей...

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/StaticLayout/LeftPanel/LeftPanel.scss
> +    @extend .link-to-game__button;
Такое делается указанием у тега нескольких элементов-модификаторов, тут @extend особо незачем:
```
<button className='link-to-game__button link-to-game__button_theme_light'>
...
```

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/StaticLayout/StaticLayout.scss
> +.main__wrapper {
И тут файл с классом разбежался

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +  children: ReactNode;
Правильнее не самому описывать children, а взять специально для этого придуманный React.PropsWithChildren

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UpperMenu/UpperMenu/UpperMenu.scss
> +.menu-list__wrapper {
Тут тоже чужой класс.

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UpperMenu/UpperMenuItem/UpperMenuItem.tsx
> +    <li className="menu-list__item" onClick={onClick} title={title ? title : text}>
Если нет title, использовать текст?
```
title={ title ?? text }
```

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UpperMenu/UpperMenuItem/UpperMenuItem.tsx
> +  const item = link ? (
Не претендую на единственное возможный стиль оформления, но я пришёл к написаниб компонентных тернарников так:
```
{ condition
  ? <NavLink to={link} className="upper-menu__link_theme_light">
      {text}
    </NavLink>
  : text
}
```
Чтобы ":" был под "?". Так и выравнивание сохраняется и кажется, что нагляднее... Но это не точно ;)

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UpperMenu/UpperMenuUserInfo/UpperMenuUserInfo.tsx
> +  const { avatar, first_name, second_name, display_name } = props;
А вот тут нехорошо смешивать camelCase и snake. Оно понятно почему - от API просочилось, но такие вещи как раз и стоит разделять, чтобы API - отдельно было, а стор - отдельно. Это должно поправиться при внедрении Редакса со стором.

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +  const { username, avatarPath, onClick, classname, text } = props;
Странное. Где-то сразу из props достаются значения, где-то нет. Хорошо бы к единому стилю свести:
Или везде так:
```
export const UserAvatar: FC<UserAvatarProps> = (props) => {
  const { username, avatarPath, onClick, classname, text } = props;
```
или так:
```
export const UserAvatar: FC<UserAvatarProps> = ({ username, avatarPath, onClick, classname, text }) => {
```

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +        className="avatar__img"
У img не указаны размеры, ни тут, ни в css - рскуем получить "прыгающую" загрузку.

2022-10-09 17:44 UTC, deadem commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +        alt={username ? username : 'Аватарка'}
Тут тоже: `avatar ?? defaul__t__Avatar` и `username ?? 'Аватарка'`

2022-10-10 11:04 UTC, zayarnaya commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
> +  children: ReactNode;
Сделала вроде. Он ругается на пустой тип, убрала вовсе.

2022-10-10 11:05 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/LeaderItem/LeaderItem.tsx
> +  ...props
А черт его знает. Я где-то натыкалась на рекомендацию везде втыкать props на всякий пожарный, не упомню уже где )

2022-10-10 11:07 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/LeaderItem/LeaderItem.tsx
> +      <UserAvatar username={name} avatarPath={avatar} classname="avatar_theme_light" onClick={onClick} />
Это я честно стырила у Романа )

2022-10-10 11:08 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/Leaderboard/LeaderBoard.scss
> +.leaderboard__wrapper {
Так я раньше на ревью отправила, чем в чатике говорили ) решила уж не вносить суету, дождать ревью и потом поправить )

2022-10-10 11:12 UTC, zayarnaya commented on packages/client/src/components/UpperMenu/UpperMenuItem/UpperMenuItem.tsx
> +  const item = link ? (
Так это все prettier переставляет и ругается на твой вариант ) я пишу либо в строку, если короткий, либо с : под ?

2022-10-10 11:12 UTC, zayarnaya commented on packages/client/src/components/UpperMenu/UpperMenuItem/UpperMenuItem.tsx
> +    <li className="menu-list__item" onClick={onClick} title={title ? title : text}>
О, так удобнее )

2022-10-10 11:24 UTC, zayarnaya commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +        className="avatar__img"
У avatar__img стоит width: 100% . А, поняла, контейнер тут не указан, а в цсс есть. Добавила classnames в класс

2022-10-10 11:24 UTC, zayarnaya commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +        alt={username ? username : 'Аватарка'}
Done

2022-10-10 11:24 UTC, zayarnaya commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +  const { username, avatarPath, onClick, classname, text } = props;
Поправила

2022-10-10 12:03 UTC, zayarnaya commented
(переработка стилей и классов отложена)

2022-10-10 14:52 UTC, deadem commented on packages/client/src/components/UserAvatar/UserAvatar.tsx
> +        className="avatar__img"
> У avatar__img стоит width: 100% . А, поняла, контейнер тут не указан, а в цсс есть. Добавила classnames в класс

А высоты-то нет.

2022-10-10 14:53 UTC, deadem approved these changes
Не забудь задачу на доработки завести. Тут OK

2022-10-10 15:15 UTC, merged