PRA-25: Сверстать страницу профиля
Kirill2511/client-server-template-with-vite pull request #13
Opened 2022-10-12 10:52 UTC by Alinshay

Страница профиля с основной информацией 

<img width="730" alt="Снимок экрана 2022-10-12 в 13 50 23" src="https://user-images.githubusercontent.com/24253636/195324017-a92914df-9105-44ac-a9eb-d68c821c3e64.png">

2022-10-12 11:43 UTC, Kirill2511 commented on packages/client/src/pages/profile/profile.tsx
> +      <Table className="profile__table">
+

2022-10-12 11:50 UTC, Kirill2511 reviewed
В целом не плохо, только таблица не нужна и глобальные цвета поправить

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Avatar/_variables.scss
>  $avatar-light-text-color: #ffffff;
var (--white) и так практически везде, эти цвета уже заданы глобально

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Avatar/avatar.scss
> +    .avatar__img {
Это отдельно по бэму

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Avatar/avatar.scss
> +    .avatar__text {
И это тоже

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/BackButton/BackButton.tsx
> +export const BackButton: React.FC<Props> = ({ to }) => {
Можно без React )

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/BackButton/_variables.scss
> +$back-button-dark-background-color: #333;
Аналогично в этом файле так же, возможно только придется их вписать в общий файл со стилями, возможно именно этого цвета нету

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Link/Link.tsx
> +export const Link: FC<LinkProps> = ({ color = 'blue', to, children, className }) => {
А тут сокращенно как раз )

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Link/_variables.scss
> +$link-light-red-color: #ff0000;
Аналогично как в других файлах с цветами

2022-10-12 11:50 UTC, Kirill2511 commented on packages/client/src/components/Table/_variables.scss
> +$table-light-border-color: #eaeaea;
Так же

2022-10-12 14:09 UTC, Alinshay commented on packages/client/src/components/Table/_variables.scss
> +$table-light-border-color: #eaeaea;
все цвета заменить на цвета из палитры?

2022-10-12 14:38 UTC, deadem commented on packages/client/src/pages/profile/profile.tsx
> +      <Table className="profile__table">
Так а грид - это же и есть таблица. Только сложная, с возможностью переставлять ячейки местами и всякой магией. Зачем брать грид там, где достаточно таблицы? Чем вам таблица не угодила? Тут же натурально сетка - то есть таблица.

2022-10-12 14:39 UTC, deadem commented on packages/client/src/pages/profile/profile.tsx
> +      <Table className="profile__table">
@romanRysev Если есть какие-то материалы почитать на эту тему - было бы очень интересно.

2022-10-12 15:03 UTC, romanRysev commented on packages/client/src/pages/profile/profile.tsx
> +      <Table className="profile__table">
@deadem я поищу вечером. Помню, в статье было 2 претензии - несемантичность и сложность с поддержкой в мобильных версиях.

2022-10-12 16:18 UTC, zayarnaya commented on packages/client/src/pages/profile/profile.tsx
> +      <Table className="profile__table">
Вот да, в мобильной версии с таблицей происходит... ничего хорошего не происходит. Но в нашем случае, возможно, и нормально будет выглядеть.

2022-10-12 16:20 UTC, zayarnaya commented on packages/client/src/components/Avatar/Avatar.tsx
>  import defaultAvatar from '../../assets/avatar.svg';
Я сама сталкивалась и вот [тут]("https://stackoverflow.com/questions/10737166/chrome-not-rendering-svg-referenced-via-img-element"), например, пишут, что хром не всегда корректно отображает svg

2022-10-12 16:45 UTC, Kirill2511 commented on packages/client/src/components/Avatar/avatar.scss
> +    .avatar__img {
.avatar__img {

2022-10-13 07:14 UTC, deadem commented on packages/client/src/components/Avatar/Avatar.tsx
>  import defaultAvatar from '../../assets/avatar.svg';
> Я сама сталкивалась и вот [тут](https://stackoverflow.com/questions/10737166/chrome-not-rendering-svg-referenced-via-img-element), например, пишут, что хром не всегда корректно отображает svg

Издеваетесь? ;)
Asked 10 years, 4 months ago

Конечно svg брать, если есть возможность. Вектор - наше всё.

2022-10-13 08:35 UTC, zayarnaya commented on packages/client/src/components/Avatar/Avatar.tsx
>  import defaultAvatar from '../../assets/avatar.svg';
Издеваюсь, конечно ) Да только я с этой проблемой не далее как в прошлом годе столкнулась. Не все сидят на свежих браузерах.

2022-10-13 09:18 UTC, deadem commented on packages/client/src/components/Avatar/Avatar.tsx
>  import defaultAvatar from '../../assets/avatar.svg';
Да не. Оно и в IE9 работает. Просто несколько капризно к формату. Нельзя вот так взять и выбросить схему, скажем. Сломается. Нужно корректный svg и тогда будет работать вообще везде, на всём, что новее 2011 года

2022-10-13 09:45 UTC, zayarnaya commented on packages/client/src/components/Avatar/Avatar.tsx
>  import defaultAvatar from '../../assets/avatar.svg';
В упор не помню откуда я тогда стандартные свг-шки брала, кажется, из бутстрапа, там уж должны норм быть. Часть там да, часть там была кривая фотошоповского происхождения (те, кто знает, щас дружно поморщились). У меня-то все видно было, а вот у заказчика - нет ))
В любом случае надо будет потом проверить весь проект на зоопарке браузеров

2022-10-13 18:05 UTC, Alinshay commented
- добавила цвета из общего файла (там все довольно хаотично пока)
- переделала компонент таблицы дивами, название меня не стала, потому что визуально это таблица

2022-10-13 18:28 UTC, Kirill2511 approved these changes

2022-10-14 11:02 UTC, deadem requested changes

2022-10-14 11:02 UTC, deadem commented on packages/client/src/components/Table/Table.tsx
> +  children: React.ReactNode;
Не нужно руками прописывать children, нужно взять PropsWithChildren или отнаследоваться от них. Кстати, рекомендую использовать interface, а type только тогда, когда интерфейса не хватает:
www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

2022-10-14 11:02 UTC, deadem commented on packages/client/src/components/Table/Table.tsx
> +  children: React.ReactNode;
И тут то же самое

2022-10-14 11:02 UTC, deadem commented on packages/client/src/components/Table/Table.tsx
> +  children: React.ReactNode | string;
И тут

2022-10-14 11:02 UTC, deadem commented on packages/client/src/pages/Profile/Profile.tsx
> +      <Table className="profile__table">
Элемент вижу. А где Блок от него? Может тут имелось в виду `profile-page__table`?

2022-10-14 11:13 UTC, Alinshay commented on packages/client/src/components/Link/Link.tsx
> +    <NavLink className={classNames(className, 'link', `link_${color}`)} to={to}>
я же тут color по умолчанию задаю, если color не пришел, то будет равен 'blue', так что он не должен быть равен undefined

2022-10-14 11:13 UTC, Alinshay commented on packages/client/src/components/BackButton/backButton.scss
> +    margin: auto;
там же в svg коде прописан ее размер, может что-то пойти не так?

2022-10-14 11:13 UTC, Alinshay commented on packages/client/src/pages/Profile/Profile.tsx
> +      <Table className="profile__table">
да, поправлю

2022-10-14 11:40 UTC, deadem commented on packages/client/src/components/BackButton/backButton.scss
> +    margin: auto;
В .png и .jpg тоже прописаны размеры ;)
https://habr.com/ru/company/ruvds/blog/497876/

2022-10-14 16:18 UTC, merged