PRA-24: Сверстать страницы редактирования профиля
Kirill2511/client-server-template-with-vite pull request #19
Opened 2022-10-17 11:03 UTC by Alinshay

Страницы с редактированием профиля

![Uploading Снимок экрана 2022-10-17 в 14.03.06.png…]()

2022-10-17 12:42 UTC, zayarnaya commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
Тут они и должны быть вложенными, или это &__input?

2022-10-17 13:28 UTC, deadem requested changes

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +      inputElem.current.addEventListener('change', (event) => {
if не нужен. Можно так:
`inputElem.current?.addEventListener(....`

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +    const withinBoundaries = (event.nativeEvent as Record<string, HTMLInputElement[]>).path.includes(popupElem.current);
Типы лучше выносить выше, вместо кастов через `as`:
```
  const handleScreenClick = useCallback((event: BaseSyntheticEvent & {nativeEvent: Record<string, HTMLInputElement[]>}) => {
    const withinBoundaries = event.nativeEvent.path.includes(popupElem.current);
```

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +.popup {
А вот тут - два компонента в одном файле. Нужно разнести в отдельные:
```
.popup {
.profile-page {
```

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +            <input ref={inputElem} type="file" id="popup__input" className="popup__input" />
У нас же есть отдельный компонент Input, зачем тут "голый" тэг?

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +            <label
Не нужно прописывать for в лейблах. Нужно обернуть Input в Label, но, вроде компонент Input это уже сам умеет.

2022-10-17 13:28 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
И вот тут каскад не нужен. Нужно указать классы миксом (ссылку в чатике раза два уже давал, про нюансы БЭМ)

2022-10-17 13:35 UTC, Alinshay commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +            <input ref={inputElem} type="file" id="popup__input" className="popup__input" />
А какие в этом плюсы? Эти компоненты вообще во всем отличаются.

2022-10-17 13:35 UTC, Alinshay commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +.popup {
У нас уже есть компонет попап, универстальный - просили сделать, чтобы везде подходил. Это стили для попапа конкретно для профиля. Могу назвать его profile-page__popup, или есть смысл ради этого создавать отдельный компонент?

2022-10-17 16:10 UTC, deadem commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +            <input ref={inputElem} type="file" id="popup__input" className="popup__input" />
А! Это поле ввода файла. Сразу не заметил. Можно специальный вид ему придумать, конечно...

2022-10-17 18:56 UTC, Alinshay commented on packages/client/src/components/ProfileLayout/ProfileLayout.tsx
> +    const withinBoundaries = (event.nativeEvent as Record<string, HTMLInputElement[]>).path.includes(popupElem.current);
<img width="948" alt="Снимок экрана 2022-10-17 в 21 56 19" src="https://user-images.githubusercontent.com/24253636/196259557-4ba8fd84-a714-42d0-b276-af74c7c96a76.png">

2022-10-18 06:56 UTC, zayarnaya commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
Ворвусь в тред. Насколько я понимаю, вопрос каскадов возникает из-за того, что в компоненте есть прописанные классы для тегов внутри. Ну как бы в принципе можно конечно их просто переопределить, но если компонент будет использоваться более одного раза на странице, то будет несимпатишно. В такой ситуации я вижу две возможности:
- таки сделать в этом случае каскад (насколько я понимаю, это не гроб-гроб-кладбище, а просто не рекомендуется),
- перелопатить компоненты и поставить там переменные заместо прописанных классов (чтоб к основному задаваемому извне классу добавлялись через __ блоки)
А еще я отдельно веселюсь нонешнему тренду на использование технологий с намеренным исключением основной фишки, в данном случае - _каскадных таблиц стилей_ без каскадов ))

2022-10-18 07:18 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
> (насколько я понимаю, это не гроб-гроб-кладбище, а просто не рекомендуется),
Оно зависит. Если, например, каскад от :hover, тогда, действительно особо не страшно. Но если каскад из классов - это именно что "гроб-гроб-кладбище".

> тренду на использование технологий с намеренным исключением основной фишки, в данном случае - каскадных таблиц стилей без каскадов
Каскады придумывались, когда компонентов даже в проекте не было.
Сейчас это выстраданная необходимость. В одном проекте 30k строк scss и пришлось отказаться от каскадов и уйти на БЭМ из-за того, что потеряли контроль за кодом: совершенно непонятно, кто отвечает за создание какой-то контрольки в css. Хуже того, что код рефактрится периодически, переименовывается и удаляется. Может быть этот каскад уже не будет вызван никогда, потому, что контроль переехала/переименована/удалена. Как это проверить? Да и просто во время правок поди найди, не зацепил ли чего-то в проекте, если в любом из компонентов может быть каскадная зависимость.

Конкретно в данном случае каскад уходит в пользу простого микса (БЭМ).

2022-10-18 07:54 UTC, zayarnaya commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
> В одном проекте у меня 30k строк scss (немного) но пришлось отказаться от каскадов и уйти на БЭМ из-за того, что потеряли контроль за кодом

В небольших проектах на годзиллион строк должны быть очень жесткие требования к коду и документированию оного, иначе как-то сам собой получается битрикс. К сожалению, обычно стадию перехода из карманного проекта в большой проворонивают )

> Конкретно в данном случае каскад уходит в пользу простого микса (БЭМ).
В этом случае да. А вот в случае, если бы надо было задать отдельный стиль скажем для .input__label, который сидит со своим заданным классом в компоненте Input? Тут без каскадов и без изменений в компоненте вообще не представляю как, разве что через @extends

2022-10-18 08:57 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
> А вот в случае, если бы надо было задать отдельный стиль скажем для .input__label, который сидит со своим заданным классом в компоненте Input? Тут без каскадов или без изменений в компоненте вообще не представляю как, разве что через @extends

Опять же, микс (псевдокод):

```scss
.input {
  padding: 10px;
}
...
.profile {
  padding: 10px;
  &__input {
    color: green;
    pagging: 20px;
  }
}
```

```tsx
interface Props {
  className?: string;
}

function Input(props: Props) {
  return (
    <label ... className={classNames('input', props.className)}>
      <input ... className='input__field'/>
    </label>
  );
}
```

И использование:

```tsx
<div className='profile`>
  <Input className='profile__input'/>
</div>
```

Если вдруг пришлось лезть глубже, чем на уровень вниз - верный признак, что это должно решаться или параметрами компонента или разбиением компонента на более мелкие.

2022-10-18 08:59 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
Параметры компонента - это свойства в props. Которые должны отвечать на вопрос "что", но не "как". То есть:

```ts
interface Props {
  syntaxCheck?: boolean; // правильно
  italic?: boolean; // неправльно
```

2022-10-18 16:10 UTC, Alinshay commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
@deadem

2022-10-18 16:14 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
> Ну вот в этом кейсе получается, что стили из .input перекрывают стили из props.className. Как повысить специфичность для стилей, которые приходят по сравнению с дефолными?

Это делается порядком включения стилей. Сначала включаются файлы со стилями компонентов, затем - стили страниц.

2022-10-18 17:06 UTC, Alinshay commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
А если это оба компонента? Есть что-то об этом почитать?

2022-10-18 18:47 UTC, deadem commented on packages/client/src/components/ProfileLayout/profileLayout.scss
> +  .profile-page__input {
> А если это оба компонента? Есть что-то об этом почитать?

Вот: https://medium.com/@innabelaya/%D0%B1%D1%8D%D0%BC-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%8E%D1%89%D0%B8%D1%85-%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%BD%D0%B5%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B8-1a21d67cf840

2022-10-19 11:45 UTC, deadem requested changes

2022-10-19 11:45 UTC, deadem commented on packages/client/src/pages/ProfileChangeInfoPage/profileChangeInfoPage.scss
> +.profile-page {
Имя класса не бьётся с именем файла. Должно совпадать (с поправкой на kebab-case vs PascalCase). И с именем компонента jsx (tsx) тоже должно совпадать.

2022-10-19 11:45 UTC, deadem commented on packages/client/src/pages/ProfileChangePasswordPage/profileChangePasswordPage.scss
> +.profile-page {
И тут имя класса не совпадает

2022-10-19 16:23 UTC, deadem requested changes
Почти. Чуть-чуть только регистр поправить и имя в Profile

2022-10-19 16:23 UTC, deadem commented on packages/client/src/pages/Profile/profile.scss
> +.profile-page {
Компонент называется Profile, файл, `profile`, а класс `profile-page`. Должно совпадать...
Видимо, должно быть так:
`Profile.scss`, `.profile`

А ещё у других страниц есть суффикс `page`. Может тут под этот стиль поправить? `ProfilePage.tsx`, компонент `Profile`, а стили `ProfilePage.scss`? (имя класса `.profile-page`)

2022-10-19 16:23 UTC, deadem commented on packages/client/src/pages/ProfileChangeInfoPage/profileChangeInfoPage.scss
> -.profile-page {
Имя файла только с большой буквы, как у tsx-компонента.

2022-10-19 16:23 UTC, deadem commented on packages/client/src/pages/ProfileChangePasswordPage/profileChangePasswordPage.scss
> -.profile-page {
Имя файла только с большой буквы, как у tsx-компонента.

2022-10-19 18:47 UTC, Alinshay commented on packages/client/src/pages/ProfileChangePasswordPage/profileChangePasswordPage.scss
> -.profile-page {
Можно было бы упомянуть об этом принципиальном моменте в самом начале, компонентов 10 назад

2022-10-20 06:12 UTC, deadem commented on packages/client/src/pages/ProfileChangePasswordPage/profileChangePasswordPage.scss
> -.profile-page {
> Можно было бы упомянуть об этом принципиальном моменте в самом начале, компонентов 10 назад

Извини, не заметил раньше.

2022-10-20 06:12 UTC, deadem approved these changes

2022-10-20 06:48 UTC, merged