PRA-27 Сверстать страницу форума
Kirill2511/client-server-template-with-vite pull request #21
Opened 2022-10-17 16:53 UTC by zayarnaya

### Какую задачу решаем
Верстка страницы форума (список тем, страница темы). И еще "Как играть" просто чтоб было.

### Скриншоты/видяшка (если есть)
![Screenshot_2022-10-17_19-44-29](https://user-images.githubusercontent.com/12728467/196236798-82c4d90e-9b45-4c60-921b-e2b62b611aeb.png)
![Screenshot_2022-10-17_19-44-40](https://user-images.githubusercontent.com/12728467/196236817-3106161f-e3ca-4a8a-991f-d656f751eb27.png)
![Screenshot_2022-10-17_19-44-54](https://user-images.githubusercontent.com/12728467/196236828-4d669306-4ba1-40a7-b69a-0130905e7f8c.png)

### TBD (если есть)

2022-10-18 07:13 UTC, Kirill2511 commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.scss
> +  .new-thread {
По бэму нельзя вкладывать другие классы стили

2022-10-18 07:13 UTC, Kirill2511 commented on packages/client/src/components/Phorum/PhorumMainPage/__MainListHeader/PhorumMainListHeader.tsx
> +      <div className="thread-list__thread_header">{threadHeader}</div>
Есть ли смысл в них? Ведь они не будут меняться

2022-10-18 07:13 UTC, Kirill2511 commented on packages/client/src/consts/prefix.ts
> +/* eslint-disable no-unused-vars */
специально убирал этот файл в utility)

2022-10-18 07:57 UTC, zayarnaya commented on packages/client/src/consts/prefix.ts
> +/* eslint-disable no-unused-vars */
я помню, что убирал, только я его потом там не нашла ) давай соберем все как есть и потом почистим.

2022-10-18 07:59 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumMainPage/__MainListHeader/PhorumMainListHeader.tsx
> +      <div className="thread-list__thread_header">{threadHeader}</div>
Есть у меня грешок излишнего усложнения ) да, можно и жестко задать, все равно если менять то в код лезьб надо

2022-10-18 11:55 UTC, zayarnaya commented on packages/client/src/App.tsx
> +              path="/phorum/thread"
Это чтоб никто не догадался ) трибьют одному из форумных движков

2022-10-18 12:14 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumThreadPage/__Reply/Reply.scss
> +      .input {
Здесь и там убрала, надеюсь, мне больше не понадобится инпутов добавлять )

2022-10-18 18:44 UTC, deadem requested changes
Какая-то каша с именованиями. Вернул, чтобы привести в соотвествие имена классов с именами файлов и названиями компонентов.
За образец можно брать вот это: https://github.com/bem/yandex-ui/blob/master/src/Button/Icon/Button-Icon.tsx

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.scss
> +.new-thread-wrapper {
И ещё один "чужой" Блок

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.scss
> +.new-thread {
И ещё один

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.scss
> +.phorum__thread-list {
Элемент без Блока?

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.scss
> +.popup-background {
И ещё один чужой

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +// import { MainListHeader } from './../__MainListHeader/PhorumMainListHeader';
Закомментированный код - удаляем. Не нужно захламлять репку.

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +  // TODO прикрутить валидацию
Писать TODO в коде - плохая практика. Вместо этого лучше сразу заводить в Лерне задачу на прикрутку

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +          </div>{' '}
А зачем тут пробел? Что-то тут не то...

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +      <div className="new-thread-wrapper">
Два Блока подряд. Вижу Блок - вижу компонент. Дробить их, безжалостно ;)
И. опять враппер... Если это вынести в отдельный компонент, то и враппер сам собой исчезнет

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +            // TODO передавать данные для новой страницы
Туду - сразу в задачу

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +            // тут я хотела поинтересоваться - так можно делать, или это совсем дно? Так в список темы добавляются, потом это будет по-другому (наверное)
Ага, этим будет заниматься Редакс. Руками не нужно будет ничего добавлять.

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__Content/PhorumMainPageContent.tsx
> +          <input type="text" placeholder="Название темы" ref={inputElem} />
А у нас же есть компонент Input...

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__MainListHeader/PhorumMainListHeader.scss
> +    &_header {
Хм... Зачем два одинаковых Элемента?... Почему не хватило одного? Непонятно.

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__MainListHeader/PhorumMainListHeader.tsx
> +    <div className="thread-list__head">
Название компонента не бьётся с именем класса. Должно совпадать всё: Имя файла, название компонента, имя CSS-класса. См. пример: https://github.com/bem/yandex-ui/blob/master/src/Button/Icon/Button-Icon.tsx

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__ThreadList/PhorumThreadList.tsx
> +    <ul className="thread-list__list">
Дальше всё то же самое - разбежались имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__ThreadListItem/PhorumThreadListItem.scss
> +.thread-list__item {
...и опять Элемент без Блока

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__ThreadListItem/PhorumThreadListItem.scss
> +.thread {
И опять чужой Блок

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__ThreadListItem/PhorumThreadListItem.scss
> +.replies {
И опять

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPage/__ThreadListItem/PhorumThreadListItem.scss
> +.last-reply {
И тут

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPage/__Post/PhorumPost.tsx
> +    <li className={classNames('post', className)} id={'#' + id}>
И что-то странное с id

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPage/__Reply/Reply.scss
> +.reply {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPage/__Reply/Reply.tsx
> +      <form className="reply">
Тут опять перепутано - это внутренности компонента, а получается, что оно внутри чужого

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/__PageCount/PhorumPageCount.scss
> +.pagecount {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/__PageCount/PhorumPageCount.tsx
> +          className="pagecount"
А это, видимо, уже Элемент

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/StaticLayout/StaticLayout.scss
>  .main {
Понятно, что это чужое, но раз уж чинить, то всё. Тут тоже не бьются имена.

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/StaticLayout/StaticLayout.tsx
>      <div className="main">
и тут

2022-10-18 18:44 UTC, deadem commented on packages/client/src/pages/HowTo/HowToPlayPage.scss
> +.rules {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/pages/HowTo/HowToPlayPage.tsx
> +    <div className="rules">
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/pages/HowTo/HowToPlayPage.tsx
> +export const HowToPlay: FC = () => {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/pages/Phorum/PhorumMainPage/PhorumMainPage.scss
> +.phorum-wrapper {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPage/__Content/PhorumThreadPageContent.tsx
> +    <div className="thread">
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/pages/Phorum/PhorumThreadPage/PhorumThreadPage.scss
> +.phorum-wrapper {
Не бьются имена

2022-10-18 18:44 UTC, deadem commented on packages/client/src/utils/makeUserProps.tsx
> +  return display_name ? display_name : `${first_name} ${second_name}`;
```
display_name ?? `${first_name} ${second_name}`
```

2022-10-19 19:44 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumThreadPage/__Post/PhorumPost.tsx
> +    <li className={classNames('post', className)} id={'#' + id}>
айди - заготовка под собственно айди, у сообщений в базе оно же должно же быть. в css не используется

2022-10-20 05:48 UTC, zayarnaya commented
Себе коммент:
откатить назад app.tsx

2022-10-20 06:09 UTC, deadem requested changes
Стало лучше, но ещё осталась путаница в именах. Вот, можно вот тут посмотреть, как канонично делается структура: https://github.com/bem/yandex-ui

Применительно к проекту:

Возьмём
`packages/client/src/components/Phorum/PhorumMainPage/PhorumMainListHeader/PhorumMainListHeader.*` ->

Компонент `PhorumMainListHeader` и класс `.phorum-main-list-header`.
Структура должна быть продолжением описания:
-> `packages/client/src/components/Phorum/PhorumMainListHeader/PhorumMainListHeader.*`

----

Возьмём
`packages/client/src/components/Phorum/PhorumMainPage/PhorumThreadList/PhorumThreadList.*` ->

Промежуточный уровень PhorumMainPage только добавляет путаницы. Он тут не нужен. Если это Page, то он должен быть не в компонентах, а в pages.

Получаем, компонент: `PhorumThreadList` и класс `.phorum-thread-list`
Структура должна быть продолжением описания:
-> `packages/client/src/components/Phorum/PhorumThreadList/PhorumThreadList.*`

2022-10-20 06:12 UTC, zayarnaya commented on packages/client/src/App.tsx
> +// const Login = React.lazy(() => import('./pages/Login/Login'));
я этот файл вообще разверну, забыла убрать из коммита.

2022-10-20 06:15 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPage/__Post/PhorumPost.tsx
> +    <li className={classNames('post', className)} id={'#' + id}>
> айди - заготовка под собственно айди, у сообщений в базе оно же должно же быть. в css не используется

Не понимаю, зачем это нужно. Если в последующем, для работы скрипта - идентификации строки по базному id, то правильнее такое сохранить в `data-id`, а не в `id`. И без решётки, конечно.

2022-10-20 06:29 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumMainPage/PhorumMainListHeader/PhorumMainListHeader.scss
> +.phorum-main-list-header {
Это папка для отделения мух от котлет, сама страница в pages лежит )

2022-10-20 06:53 UTC, deadem approved these changes

2022-10-20 06:57 UTC, merged