Pra 37 game screen+game
Kirill2511/client-server-template-with-vite pull request #25
Opened 2022-10-23 16:29 UTC by nikitapetrosian

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-10-23 17:25 UTC, zayarnaya reviewed
Пауза работает, фулл работает, круто! Посмотрим, что Владимир скажет

2022-10-23 18:15 UTC, deadem requested changes
Ощущение, что тут не правились замечания из предыдущих комментариев, а добавлялся новый функционал.
По замечаниям мало что исправлено.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/constant.ts
> +export type sequence = 'I' | 'J' | 'L' | 'O' | 'S' | 'T' | 'Z';
Имя типа у нас же везде с Заглавной буквы...

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
>    public sequence = ['I', 'J', 'L', 'O', 'S', 'T', 'Z'];
А тут получилось по сути использование типа sequence, только тип тут не упоминается и по сути, создали новый тип. Тут бы, наверное, избавиться от внешнего типа sequence, или вывести его из массива фигур.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
>        I: [
И тут нет типа.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    const matrix = this.tetrominos[(name || 'I') as sequence];
Была бы типизация, не потребовалось принудительно приводить тип. И почему нужен `|| I` тоже непонятно - как может name оказаться пустым? Какая-то ошибка в логике.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
>      const row = name === 'I' ? -1 : -2;
Странные константы. Вероятно, как-то они вычисляются?

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +      name: name || 'I',
И тут почему-то `|| I`

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +      if (this.ctx && this.ctxFigure) {
В коде полно проверок на .ctx и .canvas - они не нужны. Игра просто не должна создаваться, если нет канваса (уже писал про это)

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    if (this.paused && this.ctx && this.canvas && !this.gameOver) {
А как в режиме gameOver может быть установлена пауза? Не должна же. Тогда и проверять не придётся на второй режим.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +  private MyClick(this: any, e: any) {
Опять `any`

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +        if (this.isValidMove(matrix, this.currentTetromino.row, this.currentTetromino.col)) {
Метод вызывается в четырёх вариантах, в каждом из которых передаём своё одно из трёх значений, а остальные берутся из объекта this. Предлагаю заменить три параметра на один объект с `{ matrix, row, col }` и непереданный атрибут брать из this.

2022-10-23 18:15 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    document.addEventListener('keydown', this.myOnClick);
А кто будет отвязывать обработчик?

2022-10-24 05:42 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
> Насколько я поняла, убирать листенер хорошо бы не только на геймовер, но и на уход со страницы. Ума не приложу как это сделать, у тебя ведь класс не монтируется, а на смену локации уже другое грузиться будет. Хотя, может, и получится, раз уж он висеть остается. Правда, тогда будет висеть обработчик на hashchange :D

Вешать-снимать обработчик через useEffect

2022-10-24 07:35 UTC, zayarnaya commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
Он же не вешается внутрь класса. А снаружи на него не понимаю как корректно сослаться. Там матрешка, экземпляр класса создается внутри функции startGame при нажатии на кнопку начать игру, потом вызывается метод этого экземпляра "повесить листенер", за пределами функции к нему доступа нету или я не сообразила, внутри функции useEffect не работает. А чтоб снять листенер, нужно же точно тот же обработчик ему выдать.

2022-10-24 08:53 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
Да, всё так. Отсюда вывод:
- или должен быть Реакт-компонент, который навесит свои обработчики снаружи и будет только дёргать нужные методы класса (вверх-вниз и т.п.), а при дизмаунте всё отключит
- или у класса должны быть методы "подключить обработчики", "отключить обработчики", и внешний код должен  вызывать их явно.

Мне больше нравится первый вариант, как наиболее прозрачный.

2022-10-24 09:14 UTC, zayarnaya commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
Я пришла к тем же выводам, но вот честно - сомневаюсь, что смогу вовремя перебрать этот класс в монтирующийся компонент (пробовала по-быстрому - не выходит каменный цветок, он монтируется, конечно, но там все надо перетряхивать). Мы можем пока оставить висеть этот листенер, а я буду тихонько перебирать игру под классовый или функциональный (какая разница, все равно переписывать) компонент?

2022-10-24 09:39 UTC, deadem commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
Да переписывать-то не надо, там точечно же только поправить. Только точек больше одной ;)
И этот класс остаётся, монтирующаяся часть тоже есть. Можно просто вынести в Реакт-компонент, а если будет слишком жирно - тогда в отдельный компонент-прослойку ещё завернуть.

2022-10-24 14:38 UTC, zayarnaya commented on packages/client/src/pages/game/game-screen.ts
> +    document.removeEventListener('keydown', this.myOnClick);
Гм. Вроде получилось, теперь надо пораскинуть мозгом, как его перезапускать при новой игре )

2022-10-31 10:05 UTC, closed without merging