PRA-58, PRA-67 подключить redux store к страницам форума, игры
Kirill2511/client-server-template-with-vite pull request #32
Opened 2022-10-30 12:33 UTC by zayarnaya

### Какую задачу решаем
Брать юзера из стора (верхнее меню, форум, правое меню игры). Отправлять покуда нечего.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-01 12:18 UTC, Kirill2511 approved these changes

2022-11-01 12:18 UTC, Kirill2511 commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Не хватает ретурн. Не до конца уверен что тут вылезет такая проблема, но сам сегодня с ней столкнулся на рабочем проекте. У меня вылезло такое Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

2022-11-01 13:06 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Ценное замечание, тем более что нам надо memory leak'и найти и забить наглухо. Пойду добавлять ))

2022-11-01 13:15 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Подождите, зачем тут return? Что именно вы хотите отвязать?

2022-11-01 13:16 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Ошибка, про которую написал Кирилл, происходит, если вызвать обновление состояния на разрушенном компоненте. А тут не вижу, кто бы в этом эффекте может такое сделать.

2022-11-01 13:17 UTC, Kirill2511 commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Поэтому и написал, что не до конца уверен) Так как 1 раз столкнулся с таким)

2022-11-01 13:17 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Не надо?

2022-11-01 13:22 UTC, deadem requested changes

2022-11-01 13:22 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPageContent/PhorumMainPageContent.tsx
> +  }, []);
Подождите-ка. Но ведь данные уже в сторе, зачем их в стейт перекладывать? Тут бы просто селектором забрать данные из профиля, и всё... Они сами обновятся.

2022-11-01 13:22 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +  }, [isNewPost]);
И тут не понял, зачем нужна ручная работа со стейтом, когда профиль в сторе. Просто селектором его забрать оттуда. Можно посмотреть, как Алина сделала в своей части.

2022-11-01 13:22 UTC, deadem commented on packages/client/src/components/UpperMenu/UpperMenu.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
И тут...

2022-11-01 13:22 UTC, deadem commented on packages/client/src/pages/game/game.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
И тут...

2022-11-01 13:22 UTC, deadem commented on packages/client/src/utils/makeUserProps.tsx
> +  return display_name ? display_name : `${first_name} ${second_name}`;
А зачем тут тернарный оператор? Почему `??` недостаточно?
Ну, если должно быть именно так, как написано, то есть такой шорткат:
```
return display_name || `${first_name} ${second_name}`;
```

2022-11-01 13:29 UTC, deadem commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Тут другая засада - зачем-то ты стор перекладываешь в стейт. Просто замапить себе данные из стора, и пользуйся...

2022-11-01 13:31 UTC, zayarnaya commented on packages/client/src/utils/makeUserProps.tsx
> +  return display_name ? display_name : `${first_name} ${second_name}`;
Потому что с ?? не работает, отдает undefined емнип, я проверила. Потому и обратно поправила )

2022-11-01 13:32 UTC, zayarnaya commented on packages/client/src/pages/game/game.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Я делала не прямо оттудова, а кружным путем, чтоб если что там в профиле болтался не Андефайнд Андефайндович, а dummy user. Сделать прямо?

2022-11-01 13:35 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumThreadPageContent/PhorumThreadPageContent.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
У меня еще вопрос - там операции ведутся практически одинаковыми функциями, их имеет смысл вынести куда-нибудь в отдельный файл или так оставить?

2022-11-01 13:51 UTC, zayarnaya commented on packages/client/src/utils/makeUserProps.tsx
> +  return display_name ? display_name : `${first_name} ${second_name}`;
Да, с || работает

2022-11-01 14:05 UTC, deadem commented on packages/client/src/pages/game/game.tsx
> +    setUserProfile(store.getState().auth.user as UserProps);
Если нужен не undefined, то просто в начальное состояние стора положить брёвнышко...

2022-11-01 14:06 UTC, deadem requested changes

2022-11-01 14:06 UTC, deadem commented on packages/client/src/components/Phorum/PhorumMainPageContent/PhorumMainPageContent.tsx
> +            const userName = makeUserNameFromUser(store.getState().auth.user as UserProps);
Ой, ой! Идея была оставить userProfile, только доставать его селектором из стора. Да и приведение типа тут постоянное... Явно тут что-то не так.

2022-11-01 14:09 UTC, zayarnaya commented on packages/client/src/components/Phorum/PhorumMainPageContent/PhorumMainPageContent.tsx
> +            const userName = makeUserNameFromUser(store.getState().auth.user as UserProps);
грррррр! ругается он без приведения. про селектор не сразу поняла прост. ща поправлю

2022-11-01 16:30 UTC, deadem commented
> Без явного приведения типов ругается. Что ль в сторе его задать?

Да. Посмотрел подробнее. Тут две проблемы:
1. Нет типизации у `state.auth.user`, ну, то есть есть, он тип просто какой-то: `user: Record<string, unknown>;` должен быть конкретный тип.
2. `UserProps`, который на самом деле просто данные `User`, и которые должны быть в camelCase, а у нас оно в snake_case. Нужно поправить и свести к одному интерфейсу (и убрать /* eslint-disable camelcase */) При чтении из API прилетает camelCase и поэтому понадобится конвертация. Писал как-то про это, но, видимо, влили тогда без правок. Раз столкнулись тут, давайте тут и поправим.
3. Ещё увидел такое:
```ts
  const popupElem = useRef() as React.MutableRefObject<HTMLInputElement>;
  const inputElem = useRef() as React.MutableRefObject<HTMLInputElement>;
  const textAreaElem = useRef() as React.MutableRefObject<HTMLTextAreaElement>;
```
Вижу `as` - напрягаюсь. Тут лучше так:
```ts
  const popupElem = useRef<HTMLInputElement>(null);
  const inputElem = useRef<HTMLInputElement>(null);
  const textAreaElem = useRef<HTMLTextAreaElement>(null);
```


А ещё тут неправильно используется ref: 

```ts
      {!!isNew && (
        <Popup
          popupRef={popupElem}
...
export const Popup: FC<PopupProps> = ({
  popupRef,
  title,
  buttonText,
  onClick,
  children,
  showValidation,
  validationText,
  className,
}) => {
  return (
    <div ref={popupRef} className={classNames('popup', className)}>
```

Для пробросов ref есть специальная конструкция, `forwardRef`:

```ts
        <Popup
          ref={popupElem}
...

export const Popup = forwardRef<HTMLInputElement, PopupProps>(function Popup(
  { title, buttonText, onClick, children, showValidation, validationText, className },
  ref,
) {
  return (
    <div ref={ref} className={classNames('popup', className)}>
      <h3 className="popup__title">{title}</h3>
...
    </div>
  );
});
```

2022-11-01 16:43 UTC, zayarnaya commented
Ура, полезли править все подряд ))) нельзя просто так взять и что-то простое сделать )))) 

1, 2 - написать конвертер и поправить юзерпропс, плюс типизация того что в стор передается?

>3. Вижу as - напрягаюсь. Тут лучше так:
ты будешь смеяться, но я таки правила игру в обратную сторону, потому что оно как-то не так работало. Кажется, на possibly null ругалось. Как делать, чтоб не ругалось?

4 - правлю компонент попапа? и все остальное, где он выскакивает?

2022-11-01 18:47 UTC, zayarnaya commented
Вроде поправила, заодно в initialState забросила болванку, а то чо он. Сомнения у меня по поводу конвертера, какой-то он простой слишком. И вопрос: когда стоит использовать interface, когда type?

2022-11-02 07:00 UTC, deadem approved these changes

2022-11-02 10:42 UTC, zayarnaya commented on packages/client/src/components/UserInfo/UserInfo.tsx
>  /* eslint-disable camelcase */
ок, уберу и закидываю. Спасибо ^__^

2022-11-02 10:46 UTC, merged