PRA-82 Добавить API для лидерборда.
Kirill2511/client-server-template-with-vite pull request #33
Opened 2022-11-05 15:17 UTC by zayarnaya

### Какую задачу решаем
Добавить API для лидерборда. 
- лидеры отображаются на стр. лидерборда;
- информация отсылается после завершения игры (проигрыша);
- заведен отдельный slice в сторе;
- чтоб два раза не вставать пофикшена кнопка новой игры в панели игры.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-07 09:37 UTC, Kirill2511 commented on packages/client/src/components/Leaderboard/LeaderBoard.tsx
> +          setLoaded(true);
а отключить загрузку?)

2022-11-07 09:49 UTC, romanRysev requested changes
Круто, что не забыла про отображение возможных ошибок из запросов) Поправить осталось буквально пару мелочей)

2022-11-07 09:49 UTC, romanRysev commented on packages/client/src/components/LeaderItem/LeaderItem.tsx
> +// import { defaulAvatar, filePrefix } from '../../utils/constants';
Закомментированного кода быть не должно)

2022-11-07 10:01 UTC, zayarnaya commented on packages/client/src/components/LeaderItem/LeaderItem.tsx
> +// import { defaulAvatar, filePrefix } from '../../utils/constants';
Ага, точно )) вылавливала-вылавливала, да и пропустила ))

2022-11-07 11:41 UTC, romanRysev approved these changes

2022-11-08 08:28 UTC, deadem requested changes
В целом OK, но дублирование состояния загрузки снаружи стора хорошо бы поправить.

2022-11-08 08:28 UTC, deadem commented on packages/client/src/components/LeaderItem/LeaderItem.tsx
> +  score: string | number;
А как могут быть очки строкой?..

2022-11-08 08:28 UTC, deadem commented on packages/client/src/components/Leaderboard/LeaderBoard.tsx
> +  const leaderList = Object.values(useAppSelector((state) => state.leaders.leaderList));
Тут более корректно было бы явно обозначить, что именно выковыриваем из стора, вместо последующего преобразования:

```ts
  const leaderList = useAppSelector((state) => Object.values(state.leaders.leaderList));
```

2022-11-08 08:28 UTC, deadem commented on packages/client/src/components/Leaderboard/LeaderBoard.tsx
> +  const [isLoaded, setLoaded] = useState(false);
А это состояния дублирует стор. Не нужно контролировать стор снаружи. Лучше самого стора никто не скажет, загружены в него данные или нет.

2022-11-08 11:35 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/LeaderBoard.tsx
> +  const [isLoaded, setLoaded] = useState(false);
Я тут не стор контролирую, я хочу, чтоб со страницы запросы по триста раз не отправлялись ) проверять же при этом стор на наличие данных и отменять загрузку, если данные есть, я тоже не хочу - могут обновиться на сервере.

2022-11-08 11:38 UTC, zayarnaya commented on packages/client/src/components/Leaderboard/LeaderBoard.tsx
> +  const leaderList = Object.values(useAppSelector((state) => state.leaders.leaderList));
done

2022-11-08 11:43 UTC, zayarnaya commented on packages/client/src/components/LeaderItem/LeaderItem.tsx
> +  score: string | number;
JS все время норовит что-нибудь к строке привести, не была уверена, что на каком-то этапе это не случится ) done

2022-11-08 17:31 UTC, deadem commented on packages/client/src/components/LeaderItem/LeaderItem.tsx
> +  score: string | number;
Так именно для этого и есть TS - чтобы ненароком оно не стало строкой, а если будет пытаться, то на корню такое пресечь.

2022-11-08 19:27 UTC, deadem approved these changes
OK

2022-11-08 19:29 UTC, merged