Pra 131 one more theme
Kirill2511/client-server-template-with-vite pull request #50
Opened 2022-12-09 14:34 UTC by nikitapetrosian

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-09 16:20 UTC, deadem requested changes
скопировал комментарии в конкретные места файлов

2022-12-09 16:20 UTC, deadem commented on packages/client/.eslintrc.json
> +  "plugins": ["react", "@typescript-eslint", "prettier"],
Опять куча изменений в нерелевантных файлах

Отступы. кавычки и прочее. Это всё нужно откатить. И если менять стиль оформления - то централизованно, добавив правила линтеру.

2022-12-09 16:20 UTC, deadem commented on packages/client/src/components/LeaderItem/LeaderItem.scss
> +
изменения в нерелевантных файлах

ну и так далее

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Game.tsx
> +            {theme != 'newYear' ? (
- вот такого в коде быть не должно:
if (this.theme === 'newYear') {

Если не хватает того, что есть в теме, значит, нужно расширить возможности темизации, но не хардкодить

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Game_info.scss
> +    &_theme_newYear {
и тут...

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Game_menu.scss
> +  &_theme_newYear {
и тут...

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Tetris.tsx
> +    if (this.theme === 'newYear') {
- вот такого в коде быть не должно:
if (this.theme === 'newYear') {

Если не хватает того, что есть в теме, значит, нужно расширить возможности темизации, но не хардкодить

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Tetris.tsx
> +    // if (this.theme === 'newYear') {
закомментированный код

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Tetris.tsx
> +          if (this.theme === 'newYear') {
- вот такого в коде быть не должно:
if (this.theme === 'newYear') {

Если не хватает того, что есть в теме, значит, нужно расширить возможности темизации, но не хардкодить

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Tetris.tsx
> +            if (this.theme === 'newYear') {
- вот такого в коде быть не должно:
if (this.theme === 'newYear') {

Если не хватает того, что есть в теме, значит, нужно расширить возможности темизации, но не хардкодить

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/Tetris.tsx
> +            if (this.theme === 'newYear') {
- вот такого в коде быть не должно:
if (this.theme === 'newYear') {

Если не хватает того, что есть в теме, значит, нужно расширить возможности темизации, но не хардкодить

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/santa.ts
> +export const startSanta = (canvas: HTMLCanvasElement, index0: number, direction0: number, x0: number, y0: number) => {
После вызова startSanta остаются артефакты, которые никогда не удалятся.

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/santa.ts
> +  function init() {
После init остаются обработчики, которые никогда не удалятся

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/santa.ts
> +        if (index > 3) {
копипаста.
и ниже тоже практически точная, с очень мелкими отличиями

2022-12-09 16:20 UTC, deadem commented on packages/client/src/pages/Game/santa.ts
> +  document.removeEventListener('keydown', handleMove);
А тут второй способ отвязывания обработчиков. Должен быть один

2022-12-09 16:20 UTC, deadem commented on packages/client/src/redux/reducers/santaSlice.ts
> +export const santaSlice = createSlice({
- и кастомного редьюсера не нужно: всё можно локализовать внутри темы

2022-12-09 17:05 UTC, zayarnaya commented
... и конфликты нужно отрезолвить. Ты в чем кодишь?

2022-12-15 14:57 UTC, zayarnaya reviewed
С музыкальной темой из челюстей рождество странновато сочетается )) мне кажется, еще сыровато.

2022-12-15 14:57 UTC, zayarnaya commented on packages/client/src/pages/Game/Game.tsx
> +  // console.log(store.getState().santa.santaGameStarted);
Удалить код забыл )

2022-12-15 14:57 UTC, zayarnaya commented on packages/client/src/pages/Game/Tetris.tsx
> +    for (let row = this.playfield.length - 1; row >= 0;) {
а что тут линтеру не понравилось? убери отключалку и поправь на что предлагает )

2022-12-15 14:57 UTC, zayarnaya commented on packages/client/src/pages/Game/Tetris.tsx
> +      // setTimeout(() => {
и еще комментированный код

2022-12-15 19:32 UTC, zayarnaya requested changes
Изменения в нерелевантных файлах так и остались, как и нерешенные конфликты. А так - приятно, дети одобрили ) Настоятельно рекомендую вмержить главную ветку в твою еще до сдачи и проверить все на работоспособность.

2022-12-17 09:17 UTC, deadem requested changes
Очень хорошо! 

Осталось только добавить выключалку для setInterval и убрать `if (this.theme === 'newYear') {` (да, знаю, что это Вероника для своей темы захардкодила, но вынеси, пожалуйста, эту ветку в тему. И в свою и в тему Вероники)

2022-12-17 09:17 UTC, deadem commented on packages/client/src/pages/Game/santa.ts
>      setInterval(anim, 10);
А этот интервал кто отвяжет?

2022-12-21 13:26 UTC, deadem approved these changes

2022-12-21 18:27 UTC, zayarnaya commented
Закрываю, чтобы не болтался

2022-12-21 18:27 UTC, closed without merging